[[redirects]]
  from = "/og"
  to = "/.netlify/functions/og"
  status = 200
  force = true

[[redirects]]
  from = "/index.css"
  to = "/index.css"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
