[build]
  publish = "static"
  functions = "netlify/functions"
  edge_functions = "./netlify/edge-functions-disabled"

[dev]
  functions = "netlify/functions"
  publish = "static"

[[redirects]]
  from = "/og"
  to = "/.netlify/functions/og"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
